# Generated by Django 4.2.14 on 2024-09-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('branch_code', models.CharField(max_length=5, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('currency_sign', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('branch_purchased_at', models.CharField(max_length=100)),
                ('tenor', models.PositiveIntegerField(blank=True, choices=[(91, '91 Days'), (181, '181 Days'), (364, '1 Year'), (732, '2 Years'), (1098, '3 Years')], null=True)),
                ('customer_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maturity_instruction', models.PositiveIntegerField(blank=True, choices=[(1, 'Pay Principal and Interest on Maturity'), (2, 'Roll - Over with Interest on Maturity'), (3, 'Roll - Over Principal only on Maturity')], null=True)),
                ('lcy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='t_bill_files/')),
                ('status', models.CharField(choices=[(0, 'Not Running'), (1, 'Running')], default='0', max_length=20)),
                ('roll_over_instruction', models.CharField(choices=[('1', 'Roll-Over'), ('0', 'Do Not Roll-Over')], default='None', max_length=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_domicile_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.branchs')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.customerinformation')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.currency')),
            ],
        ),
    ]
