# Generated by Django 5.0 on 2024-10-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('branch_code', models.CharField(max_length=5, unique=True)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('currency_sign', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaturedTBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255, unique=True)),
                ('branch_purchased_at', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('csd_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lcy_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issue_date', models.DateTimeField()),
                ('maturity_date', models.DateTimeField()),
                ('requested_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('ccy', models.CharField(blank=True, max_length=10, null=True)),
                ('dr_cr', models.CharField(blank=True, max_length=2, null=True)),
                ('transaction_details', models.TextField(blank=True, null=True)),
                ('lcy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acc_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('fcy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('related_account', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sn', models.IntegerField(blank=True, null=True)),
                ('instrument', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('branch_purchased_at', models.CharField(max_length=100)),
                ('account_domicile_branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('tenor', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=50)),
                ('customer_amount', models.CharField(max_length=20)),
                ('maturity_instruction', models.CharField(max_length=50)),
                ('lcy_amount', models.CharField(max_length=20)),
                ('interest_rate', models.CharField(max_length=20)),
                ('discount_rate', models.CharField(max_length=20)),
                ('face_value', models.CharField(max_length=20)),
                ('issue_date', models.CharField(max_length=50)),
                ('maturity_date', models.CharField(max_length=50)),
                ('roll_over_instruction', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('branch_purchased_at', models.CharField(max_length=100)),
                ('tenor', models.PositiveIntegerField(blank=True, choices=[(91, '91 Days'), (181, '181 Days'), (364, '1 Year'), (732, '2 Years'), (1098, '3 Years')], null=True)),
                ('customer_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lcy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('maturity_instruction', models.PositiveIntegerField(blank=True, choices=[(1, 'Pay Principal and Interest on Maturity'), (2, 'Roll - Over with Interest on Maturity'), (3, 'Roll - Over Principal only on Maturity')], null=True)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='t_bill_files/')),
                ('status', models.CharField(default='0', max_length=20)),
                ('roll_over_instruction', models.CharField(choices=[('0', 'Do Not Roll-Over'), ('1', 'Roll-Over'), ('2', 'Terminate')], default='None', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_domicile_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.branchs')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.customerinformation')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.currency')),
            ],
        ),
    ]
