# Generated by Django 5.0 on 2024-10-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_codeentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeEntry',
            new_name='BOG_Weekly_Code',
        ),
    ]
