# Generated by Django 4.2.14 on 2024-09-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_alter_treasurybills_roll_over_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=255)),
                ('branch_purchased_at', models.CharField(max_length=100)),
                ('account_domicile_branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('tenor', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=50)),
                ('customer_amount', models.CharField(max_length=20)),
                ('maturity_instruction', models.CharField(max_length=50)),
                ('lcy_amount', models.CharField(max_length=20)),
                ('interest_rate', models.CharField(max_length=20)),
                ('discount_rate', models.CharField(max_length=20)),
                ('face_value', models.CharField(max_length=20)),
                ('issue_date', models.CharField(max_length=50)),
                ('maturity_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('roll_over_instruction', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='treasurybills',
            name='roll_over_instruction',
            field=models.CharField(choices=[('0', 'Do Not Roll-Over'), ('1', 'Roll-Over'), ('2', 'Terminate')], default='None', max_length=100),
        ),
    ]
