# Generated by Django 5.0 on 2024-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_rename_codeentry_bog_weekly_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurybills',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
