# Generated by Django 4.2.14 on 2024-09-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_withdrawal_alter_treasurybills_roll_over_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='status',
        ),
    ]
