# Generated by Django 5.0 on 2024-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr')], max_length=20, null=True)),
                ('surname_or_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('residential_status', models.CharField(blank=True, choices=[('Resident Ghanaian', 'Resident Ghanaian'), ('Resident Foreigner', 'Resident Foreigner'), ('Non Resident Ghanaian', 'Non Resident Ghanaian'), ('Non Resident Foreigner', 'Non Resident Foreigner')], default='', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth_or_incorporation_of_business', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Birth Certificate', 'Birth Certificate'), ('Voters Card', 'Voters Card'), ('Certificate of Incorporation', 'Certificate of Incorporation'), ('Drivers License', 'Drivers License')], default='', max_length=255, null=True)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(max_length=13, unique=True)),
                ('account_branch', models.CharField(max_length=13)),
                ('csd_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to='ID/')),
                ('csd_file', models.FileField(upload_to='CSD/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
