# Generated by Django 5.0 on 2024-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinformation',
            name='account_branch',
            field=models.CharField(blank=True, choices=[('101', 'Airport')], default='', max_length=255, null=True),
        ),
    ]
